name: CI
on:
  push:
    branches:
      - master
env:
  AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        publish_dir: ./build
    - name: Test Env
      run: |
        echo 'The GitHub Action Secret will be masked:  '
        echo ${{ secrets.GITHUB_TOKEN }}
        echo 'Testing secret if its masked: '
        echo ${{ secrets.AWS_ACCESS_KEY }}
        # echo 'Trick to echo GitHub Actions Secret: '
        # echo ${{secrets.AWS_ACCESS_KEY}} | sed 's/./& /g'
    # - name: Install Packages
    #   run: npm ci
    # - name: Build page
    #   working-directory: ./src
    #   run: npm run build
    # - name: Deploy
    #   uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #     SOURCE_DIR: "build"
        # aws s3 sync build/ s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }} --debug
        # aws cloudfront create-invalidation --distribution-id ${{ secrets.JORDAN_CLOUDFRONT_DISTRIBUTION_ID }} --paths \"/*\" --debug

# This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#       # Runs a set of commands using the runners shell
#       - name: Install
#         run: npm ci
#       - name: Build
#         run: npm run build --if-present
#   deploy:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     needs: build
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#         with:
#           profile: jordan
#           region: ${{ secrets.AWS_REGION }}
#           key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#       # Runs a set of commands using the runners shell
#       - name: Deploy
#         run: npm run deploy
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
#           SOURCE_DIR: "build"
